# Copyright (c) The btclib developers
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""Core's `feature_settings`, one body over either node.

Read from Core's `test/functional/feature_settings.py` (`0654511e1b93`,
2026-06-17), an option and the disk
([ISS 14](https://github.com/btclib-org/bitcoin-node-tests/issues/14)):
the settings file a node keeps in its chain's data directory
(`Capability.SETTINGS_FILE`). A node writes it at its first start,
holding only Core's `_warning_`. The values in it are logged at the next
start, each name the node does not use with a warning, and the node
leaves them in the file when it stops. A file that is not valid JSON,
not a JSON object, or that holds a key twice refuses the start in Core's
own words. `-nosettings`, on the command line or in `bitcoin.conf`,
starts the node over such a file, and `-settings=<path>` reads another
file instead. The log is read through `Capability.DEBUG_LOG`.

The second test is Core's `test_wallet_settings`
(`Capability.NODE_WALLET`): a `wallet` value in the file that is not a
list of strings refuses the start, for each value Core's list names.

What differs from Core's file:

- Core's harness writes a `bitcoin.conf` and the test appends
  `nosettings=1` to it, in its `[regtest]` section; neither adapter
  writes one, so the test writes that section and that line alone;
- the invalid-JSON refusal's wording is read from the running build's
  `getnetworkinfo` `version`: a build before `v31.1`, `v29.4` and
  `v30.3` among them, blames "disk corruption or a crash", and `v31.1`
  and Core's `master` word it as the pin's file expects. The threshold
  is `v31.1`, the release the change was backported to; it answers
  wrongly only for a `master` build taken after the move to `31.99` and
  before the change's merge,
  bitcoin/bitcoin@794befd4b06dcace1adbdb15e65bba1667f9bc15;
- Core matches each file refusal as a regular expression searched in
  stderr (`ErrorMatch.PARTIAL_REGEX`); here each is a substring of it,
  its dots matching only dots.

A refusal is matched against the stderr of a start that exited with a
code other than `0` before its RPC answered, as
`feature_includeconf_test.py` matches one.

`feature_settings_bitcoind_test.py` and
`feature_settings_btclib_node_test.py` run it,
`tests/integration/conftest.py`'s own module docstring having how.
"""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING

import pytest

from bitcoin_node_tests.bitcoind import BitcoindAdapter
from bitcoin_node_tests.capability import Capability, require
from bitcoin_node_tests.debug_log import assert_debug_log
from bitcoin_node_tests.node import free_ports

if TYPE_CHECKING:
    from pathlib import Path

    from bitcoin_node_tests.btclib_node import BtclibNodeAdapter
    from bitcoin_node_tests.capability import SkipCounts
    from bitcoin_node_tests.node import NodeAdapter
    from tests.conftest import AdapterFactory

__all__ = [
    "the_settings_file_is_written_read_and_checked",
    "the_wallet_setting_takes_only_strings",
]

# Core's own `default_settings`, `CLIENT_NAME` being `Bitcoin Core`
_DEFAULT_SETTINGS = {
    "_warning_": (
        "This file is automatically generated and updated by Bitcoin Core. "
        "Please do not edit this file while the node is running, as any "
        "changes might be ignored or overwritten."
    )
}

# the values Core's test writes, and the log lines they are read with
_VALUES = {"string": "string", "num": 5, "bool": True, "null": None, "list": [6, 7]}
_VALUES_LOGGED = [
    "Ignoring unknown rw_settings value bool",
    "Ignoring unknown rw_settings value list",
    "Ignoring unknown rw_settings value null",
    "Ignoring unknown rw_settings value num",
    "Ignoring unknown rw_settings value string",
    'Setting file arg: string = "string"',
    "Setting file arg: num = 5",
    "Setting file arg: bool = true",
    "Setting file arg: null = null",
    "Setting file arg: list = [6,7]",
]

# Core's own `expected_msg` for each refusal of a malformed file; the
# invalid-JSON one by the build's `version`, `_STORAGE_ERROR_VERSION` on
_INVALID_JSON = (
    "does not contain valid JSON. This may be caused by a crash, power loss, "
    "full disk, or storage error"
)
_INVALID_JSON_BEFORE = (
    "does not contain valid JSON. This is probably caused by disk corruption or a crash"
)
_STORAGE_ERROR_VERSION = 310100
_NON_OBJECT = 'Found non-object value "string" in settings file'
_DUPLICATE_KEY = "Found duplicate key key in settings file"

# Core's own `expected_msgs` for each start that ignores or moves the file
_NOSETTINGS_ARG = "Command-line arg: settings=false"
_NOSETTINGS_CONF = "Config file arg: [regtest] settings=false"
_ALTSETTINGS = 'Setting file arg: key = "value"'

# Core's own `test_wallet_settings`: every value refused, and the message
_WALLET_VALUES: list[list[object]] = [
    [10],
    [True],
    [[]],
    [{}],
    ["w1", 10],
    ["w1", False],
]
_WALLET_REFUSED = (
    "Error: Invalid value detected for '-wallet' or '-nowallet'. '-wallet' "
    "requires a string value, while '-nowallet' accepts only '1' to disable "
    "all wallets"
)

# `_wait_for_rpc`'s own wording (`node.py`), split into the exit code and
# the stderr it carries
_EARLY_EXIT = re.compile(
    r"node process exited with (-?\d+) before its RPC answered -- stderr: (.*)",
    re.DOTALL,
)


def _node(
    make_adapter: AdapterFactory,
    cls: type[BitcoindAdapter | BtclibNodeAdapter],
    executable: str,
    datadir: Path,
) -> BitcoindAdapter | BtclibNodeAdapter:
    """Return a node over `datadir`, not yet started, on ports of its own.

    :param make_adapter: the session's own adapter factory.
    :param cls: `BitcoindAdapter` or `BtclibNodeAdapter`.
    :param executable: the node's binary, or the interpreter running it.
    :param datadir: the data directory the test writes its files into.
    """
    rpc_port, p2p_port = free_ports(2)
    return make_adapter(cls, executable, datadir, rpc_port, p2p_port)


def _debug_log(
    node: BitcoindAdapter | BtclibNodeAdapter, skip_counts: SkipCounts
) -> Path:
    """Return the log the test reads, or skip where the node keeps none.

    :raises TypeError: `node` declares `Capability.DEBUG_LOG` without
        being the adapter that names a `debug_log_path`.
    """
    require(Capability.DEBUG_LOG, node.capabilities, skip_counts)
    if not isinstance(node, BitcoindAdapter):
        err_msg = f"{type(node).__name__} declares DEBUG_LOG, naming no debug.log"
        raise TypeError(err_msg)
    return node.debug_log_path


def _refused_stderr(node: NodeAdapter, extra_args: list[str]) -> str:
    """Start `node` with `extra_args`, and return the stderr it exits with.

    Core's own `assert_start_raises_init_error`: the start fails, with an
    exit code other than `0`, before its RPC ever answers.

    :param node: a node not running.
    :param extra_args: what to start it with.
    """
    try:
        with pytest.raises(RuntimeError) as refused:
            node.restart(extra_args)
    finally:
        node.stop()
    early_exit = _EARLY_EXIT.fullmatch(str(refused.value))
    assert early_exit is not None
    assert int(early_exit[1]) != 0
    return early_exit[2].strip()


def _version(node: NodeAdapter) -> int:
    """Return `getnetworkinfo`'s own `version`."""
    info = node.rpc.call("getnetworkinfo")
    assert isinstance(info, dict)
    version = info["version"]
    assert isinstance(version, int)
    return version


def the_settings_file_is_written_read_and_checked(
    make_adapter: AdapterFactory,
    cls: type[BitcoindAdapter | BtclibNodeAdapter],
    executable: str,
    tmp_path: Path,
    skip_counts: SkipCounts,
) -> None:
    """Core's own `run_test`, in Core's own order, less its wallet half.

    :param make_adapter: the session's own adapter factory.
    :param cls: `BitcoindAdapter` or `BtclibNodeAdapter`.
    :param executable: the node's binary, or the interpreter running it.
    :param tmp_path: where the node's own data directory goes.
    :param skip_counts: the session's own tally.
    """
    datadir = tmp_path / "datadir"
    node = _node(make_adapter, cls, executable, datadir)
    require(Capability.SETTINGS_FILE, node.capabilities, skip_counts)
    log = _debug_log(node, skip_counts)
    settings = datadir / "regtest" / "settings.json"
    conf = datadir / "bitcoin.conf"

    # the default settings file, written at the first start
    try:
        node.start()
        version = _version(node)
    finally:
        node.stop()
    assert json.loads(settings.read_text(encoding="utf-8")) == _DEFAULT_SETTINGS

    # the values parsed and logged, and left in the file on shutdown
    settings.write_text(json.dumps(_VALUES), encoding="utf-8")
    with assert_debug_log(log, _VALUES_LOGGED):
        try:
            node.start()
        finally:
            node.stop()
    written = json.loads(settings.read_text(encoding="utf-8"))
    assert written == {**_DEFAULT_SETTINGS, **_VALUES}

    # a malformed file refuses the start
    invalid_json = (
        _INVALID_JSON if version >= _STORAGE_ERROR_VERSION else _INVALID_JSON_BEFORE
    )
    settings.write_text("invalid json", encoding="utf-8")
    assert invalid_json in _refused_stderr(node, [])
    settings.write_text('"string"', encoding="utf-8")
    assert _NON_OBJECT in _refused_stderr(node, [])
    settings.write_text('{"key": 1, "key": 2}', encoding="utf-8")
    assert _DUPLICATE_KEY in _refused_stderr(node, [])

    # -nosettings on the command line, then in bitcoin.conf, over that file
    with assert_debug_log(log, [_NOSETTINGS_ARG]):
        try:
            node.restart(["-nosettings"])
        finally:
            node.stop()
    with conf.open("a", encoding="utf-8") as conf_file:
        conf_file.write("[regtest]\nnosettings=1\n")
    with assert_debug_log(log, [_NOSETTINGS_CONF]):
        try:
            node.start()
        finally:
            node.stop()

    # another settings file, named on the command line
    altsettings = datadir / "altsettings.json"
    altsettings.write_text('{"key": "value"}', encoding="utf-8")
    with assert_debug_log(log, [_ALTSETTINGS]):
        try:
            node.restart([f"-settings={altsettings}"])
        finally:
            node.stop()


def the_wallet_setting_takes_only_strings(
    make_adapter: AdapterFactory,
    cls: type[BitcoindAdapter | BtclibNodeAdapter],
    executable: str,
    tmp_path: Path,
    skip_counts: SkipCounts,
) -> None:
    """Core's own `test_wallet_settings`: a `wallet` value not a string refused.

    :param make_adapter: the session's own adapter factory.
    :param cls: `BitcoindAdapter` or `BtclibNodeAdapter`.
    :param executable: the node's binary, or the interpreter running it.
    :param tmp_path: where the node's own data directory goes.
    :param skip_counts: the session's own tally.
    """
    datadir = tmp_path / "datadir"
    node = _node(make_adapter, cls, executable, datadir)
    require(Capability.SETTINGS_FILE, node.capabilities, skip_counts)
    require(Capability.NODE_WALLET, node.capabilities, skip_counts)
    settings = datadir / "regtest" / "settings.json"

    # a wallet for the list to name
    try:
        node.start()
        node.rpc.call("createwallet", ["w1"])
    finally:
        node.stop()

    for wallets_data in _WALLET_VALUES:
        settings.write_text(json.dumps({"wallet": wallets_data}), encoding="utf-8")
        refused = _refused_stderr(node, [f"-settings={settings}"])
        assert refused == _WALLET_REFUSED, wallets_data
